/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    screens: {
      xs: "400px",
      sm: "768px",
      md: "900px",
      lg: "1100px",
      xl: "1200px",
      "2xl": "1400px",
      "3xl": "1600px",
    },
    container: {
      center: true,
      padding: "1.5rem",
    },
    extend: {
      fontSize: {
        h1: ["3.429rem", { lineHeight: "3.772rem" }],
        h2: ["2.25rem", { lineHeight: "2.475rem" }],
        h3: ["1.75rem", { lineHeight: "2.2rem" }],
        h4: ["1.5rem", { lineHeight: "1.65rem" }],
        lg: ["1.5rem", { lineHeight: "1.375rem" }],
        body: ["1.25rem", { lineHeight: "1.375rem" }],
        sm: ["1rem", { lineHeight: "1.1rem" }],
        xs: ["0.875rem", { lineHeight: ".9625rem" }],
      },
      fontWeight: {
        thin: "300",
        light: "340",
        regular: "400",
        medium: "500",
      },
      letterSpacing: {
        "body-light": "-0.025rem",
        h3: "-0.04rem",
        h2: "-0.0315rem",
        h4: "-0.003rem",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        errorRing: "hsl(var(--error-ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        pinto: {
          DEFAULT: "#246645",
          green: "#246645",
          "red-1": "#FCEFEF",
          "red-2": "#FF0000",
          "green-1": "#D8F1E2",
          "green-2": "#00C767",
          "green-3": "#246645",
          "green-4": "#387F5C",
          "green-5": "#0CB763",
          "orange-1": "#FFF6EA",
          "off-green": "#9A9F6C",
          "off-green-bg": "#EFEEDF",
          "gray-1": "#F8F8F8",
          "gray-2": "#D9D9D9",
          "gray-3": "#B9B9B9",
          "gray-4": "#9C9C9C",
          "gray-5": "#404040",
          "gray-6": "#6E6E6E",
          "gray-blue": "#E9F0F6",
          "off-white": "#FCFCFC",
          "morning-yellow-0": "#E9E7E0",
          "morning-yellow-1": "#FEE18C",
          "morning-yellow-2": "#F1F88C",
          "warning-yellow": "#DCB505",
          "warning-orange": "#ED7A00",
          primary: "#000000",
          secondary: "#404040",
          light: "#9C9C9C",
          lighter: "#B9B9B9",
          success: "#00C767",
          error: "#FF0000",
        },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 0.5rem)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 0.125rem)",
        sm: "calc(var(--radius) - 0.25rem)",
      },
      fontFamily: {
        pinto: ["Pinto", "system-ui", "sans-serif"],
        roboto: ["Roboto", "system-ui", "sans-serif"],
        menlo: ["Menlo", "Monaco", "Courier New", "monospace"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(-4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.15s ease-out",
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    ({ addComponents }) => {
      addComponents({
        ".pinto-h1": { "@apply text-h1 font-thin tracking-normal": {} },
        ".pinto-h2": { "@apply text-h2 font-thin tracking-h2": {} },
        ".pinto-h3": { "@apply text-h3 font-light tracking-h3 sm:text-[2rem]": {} },
        ".pinto-h4": { "@apply text-h4 font-regular tracking-h4": {} },
        ".pinto-lg": { "@apply text-lg font-light": {} },
        ".pinto-body": { "@apply text-body font-regular": {} },
        ".pinto-body-light": { "@apply text-body font-light tracking-body-light": {} },
        ".pinto-body-bold": { "@apply text-body font-medium": {} },
        ".pinto-sm": { "@apply text-sm font-regular": {} },
        ".pinto-sm-light": { "@apply text-sm font-light": {} },
        ".pinto-sm-bold": { "@apply text-sm font-medium": {} },
        ".pinto-xs": { "@apply text-xs font-light": {} },
      });
    },
    require("@tailwindcss/typography"),
  ],
};
